development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:ef80629b4b764b1f89a569e71ea01b3c@pike.redistogo.com:10330/
  channel_prefix: Acme-Messaging_production
